//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód vygeneroval nástroj.
// </auto-generated>
//------------------------------------------------------------------------------
namespace WebApplication1
{
    public partial class Triangle
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Label lblA;
        protected global::System.Web.UI.WebControls.TextBox txtA;

        protected global::System.Web.UI.WebControls.Label lblB;
        protected global::System.Web.UI.WebControls.TextBox txtB;

        protected global::System.Web.UI.WebControls.Label lblC;
        protected global::System.Web.UI.WebControls.TextBox txtC;

        protected global::System.Web.UI.WebControls.Button btnCheck;

        protected global::System.Web.UI.WebControls.Label lblTriangleResult;

        protected global::System.Web.UI.WebControls.Button btnBack;
    }
}